version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: orisod_db
    restart: always
    environment:
      POSTGRES_USER: orisod_user
      POSTGRES_PASSWORD: orisod_password
      POSTGRES_DB: orisod_calls
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
